[project]
name = "google-review-scraping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "emoji>=2.14.0",
    "loguru>=0.7.3",
    "pandas>=2.2.3",
    "playwright>=1.49.1",
]
